[package]
name = "arm11"
version = "0.1.0"
authors = ["Ashvin Arsakularatne <aa9220@ic.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
